image: microsoft/dotnet:latest

stages:
    - build
    - test

before_script:
    - "cd KrisHemenway.TVShows"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"

test:
    stage: test
    script: 
        - "dotnet test"